# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreAnimation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreAnimation
  pod 'Masonry'
end
